language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27,coverage
    - python: 3.6
      env: TOXENV=py36,coverage
    - python: 3.6
      env: TOXENV=flake8,pylint

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get -y install python-fontforge ttfautohint
- sudo apt-get install mono-runtime libmono-system-windows-forms4.0-cil
- pip install --upgrade pip

install:
- export LD_LIBRARY_PATH=/usr/local/lib
- export PATH=$PATH:prebuilt/fval/
- export LD_PRELOAD=prebuilt/custom_freetype/lib/libfreetype.so
- pip install tox

script:
- tox
